"""add image snapshot to order items

Revision ID: 55564ff3ea73
Revises: 97786481602c
Create Date: 2026-04-18 17:53:18.209629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55564ff3ea73'
down_revision: Union[str, Sequence[str], None] = '97786481602c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('image_url_snapshot', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'image_url_snapshot')
    # ### end Alembic commands ###
