"""add product aliases

Revision ID: 94ab49158df0
Revises: 1a3ebe90de97
Create Date: 2026-04-17 16:18:54.115818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ab49158df0'
down_revision: Union[str, Sequence[str], None] = '1a3ebe90de97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_aliases_alias'), 'product_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_product_aliases_id'), 'product_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_product_aliases_product_id'), 'product_aliases', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_aliases_product_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_alias'), table_name='product_aliases')
    op.drop_table('product_aliases')
    # ### end Alembic commands ###
